### ISSUE TITLE
8월 6일 (금요일) 2시간 코딩 모의 코딩 테스트 진행 예정

### ISSUE THREAD

**Issue by Hmgi** [Hmgi/Coding-Test-Study#16]
가능 한 시간대 코멘트로 달아 주시기 바랍니다.

문제는 파이썬으로 풀이하며 문제 수는 2문제 입니다.

**Comment by uhcho2020** [comment]
전 시간대 다 가능합니다. 시간 공지 해주시기 바랍니다

**Comment by Hmgi** [comment]
19:30 ~ 21: 00 까지 한시간 반 진행할 예정입니다. 준비해주시기 바랍니다
