### ISSUE TITLE
프로그래머스 1단계 안푼 문제 수 체크

### ISSUE THREAD

**Issue by Hmgi** [Hmgi/Coding-Test-Study#6]
@uhcho2020 
프로그래머스 1단계, C언어, 안푼 문제 체크 후 캡쳐 사진을 업로드 해주시면 감사하겠습니다.

-이슈에 사진 업로드 방법은 github issues image upload 검색을 참조해주시면 감사하겠습니다.

**Comment by uhcho2020** [comment]
프로그래머스 1단계, C언어, 안푼 문제 캡쳐 사진입니다
![image](https://user-images.githubusercontent.com/28240029/125418474-4027e892-a4ea-4d1b-b14f-3e12b212400c.png)

**Comment by Hmgi** [comment]
확인했습니다.
2단계 부터는 알고리즘 설명을 추가 하기 때문에 7일 중 5일 문제 3문항으로 문제를 풀며 나머지 4일은 문제에 대한 풀이와 알고리즘을정리하여 작성하시면 됩니다.
